### ISSUE TITLE
"Else if" instead of "if" for Poisson sampling in maps to observables

### ISSUE THREAD

**Issue by Linc-tw** [hsxavier/flask#2]
Hello, 
https://github.com/hsxavier/flask/blob/fe5d1c903d4fcaaf49765fc67e67480922d4322d/src/flask.cpp#L673
L673: I believe that it should be a "else if" here. Otherwise L674 might revisit that pixel again and assign some galaxies to it.

**Comment by hsxavier** [comment]
You are correct, thanks for pointing this out! 
I chose to fix this by changing line 672 from mapf[i][j]=0.0 to mapf[i][j]=-1.0. The "else if" solution would keep a pixel in the masked region from being masked if it happens to have density contrast <-1.
