### ISSUE TITLE
local logging function declarations have different type

### ISSUE THREAD

**Issue by ntessore** [hsxavier/flask#3]
The logging function `warning` is locally declared in the functions in ParameterList.cpp, 

```cpp
int ParameterList::findpar (std::string word) const {
  using namespace ParDef;
  void warning(const std::string message);
  ...
```

but with a different return type than its declaration in Utilities.hpp,

```cpp
int warning (const std::string message);
```

which leads to errors in homebrew gcc 8.2.0. It compiles after removing the local declarations of `warning` (and `error`), which seem unnecessary.

**Comment by hsxavier** [comment]
Thanks for the feedback. In the last commit I removed these unnecessary
(and contradictory) declarations.
