### ISSUE TITLE
Cannot use latest version of cfitsio with flask

### ISSUE THREAD

**Issue by prinewgirl-zz** [hsxavier/flask#5]
When compiling flask with latest version of cfitsio, I have the following error:
![Screenshot from 2019-05-01 09-06-10](https://user-images.githubusercontent.com/6698424/57025620-0aea9b00-6c0e-11e9-8c74-9fa64bb62e64.png)

**Comment by hsxavier** [comment]
I think your screenshot does not show the error message. However, it does
show the makefile, and it seems that the path to CXXFITS and LDFITS are
probably wrong. You should change them to the location where the cfitsio
headers and libraries are located. This is probably the cfitsio directory.
