### ISSUE TITLE
!! ERROR!  SelectionFunction.load: SELEC_TYPE fraction of gals not implemented yet. !!

### ISSUE THREAD

**Issue by pbarya** [hsxavier/flask#6]
I am trying to fix the number of galaxies in out catalog.
Setting galaxy density =0.01 h/ mpc^3 
GALDENSITY:        0.01       
 SELEC_TYPE = 1 

I am getting the following error:  
SHEAR_MAP_OUT written to tgss/shearmap.dat
Reading selection functions from files...                 
!! ERROR!  SelectionFunction.load: SELEC_TYPE fraction of gals not implemented yet. !!

**Comment by hsxavier** [comment]
The option `SELEC_TYPE: 1` is not implemented yet (and likely will never be). I suggest using `SELEC_TYPE: 0` and checking section 3.1.5 of the [FLASK manual](https://github.com/hsxavier/flask/blob/master/doc/flask_manual.pdf) for how to fix the galaxy density.

**Comment by pbarya** [comment]
I see thanks. Thanks! 
I am able to control density by changing the f(z) normalization in radial selection functions file.
